// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolicitudesService.Infrastructure.Data;

#nullable disable

namespace SolicitudesService.Infrastructure.Migrations
{
    [DbContext(typeof(SolicitudesServiceDbContext))]
    partial class SolicitudesServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolicitudesService.Core.Entities.SolicitudDocumentos", b =>
                {
                    b.Property<int>("IdSolicitudDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudDocumento"));

                    b.Property<bool>("EstaAprobada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSolicitudDocumento");

                    b.ToTable("SolicitudesDocumentos", (string)null);
                });

            modelBuilder.Entity("SolicitudesService.Core.Entities.SolicitudHorasExtra", b =>
                {
                    b.Property<int>("IdSolicitudHorasExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudHorasExtra"));

                    b.Property<int>("CantidadHoras")
                        .HasColumnType("int");

                    b.Property<bool>("EstaAprobada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitudHorasExtra");

                    b.ToTable("SolicitudesHorasExtra", (string)null);
                });

            modelBuilder.Entity("SolicitudesService.Core.Entities.SolicitudPersonal", b =>
                {
                    b.Property<int>("IdSolicitudPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudPersonal"));

                    b.Property<bool>("EstaAprobada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdSolicitudPersonal");

                    b.ToTable("SolicitudesPersonales", (string)null);
                });

            modelBuilder.Entity("SolicitudesService.Core.Entities.SolicitudVacaciones", b =>
                {
                    b.Property<int>("IdSolicitudVacaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudVacaciones"));

                    b.Property<int>("DiasRestantes")
                        .HasColumnType("int");

                    b.Property<int>("DiasSolicitados")
                        .HasColumnType("int");

                    b.Property<bool>("EstaAprobada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitudVacaciones");

                    b.ToTable("SolicitudesVacaciones", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
